rvm: 1.9.3
env:
- PUPPET_GEM_VERSION=3.6
- PUPPET_GEM_VERSION=3.7
notifications:
  hipchat:
    rooms:
      secure: OoKJMDdxaVJJBeLSyGN1Yf3ks189c5rZ2wj8OtlqkHtYlWDr8ViumJTMxWFNl5EUbx+BKCMArTsx9u4ahYvdJzaDLNaKD0l4hXQ6NdxrziI8y2boQdAeRXzPK02jRo3b3GG3Nmia7k5xkXF7Oztb5kT/q5hPM+Lbrq+CEGmi60U=
after_script: "bundle exec rake build"
before_deploy: "puppet module build"
deploy:
  provider: releases
  api_key:
    secure: gt3Nm5gKBKGtYSJAA5vRA9f3StLf6wz2UgWSjyzvQuXDGXEArcI6bQCbIRV1+2KaeDul86kTS8Xt7N4SO7/mmogdHZ7XAw7Y5MuRSNFMCk3ch5VUbOTT8vuBhX7UGr41j3EJndfRilHyDmi7DfT0L4kmieiqgODuH9yEJ+ux3FY=
  file: pkg/puppet-xldeploy-1.2.3.tar.gz
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs/puppet-xldeploy
script:
  - "rake test SPEC_OPTS='--format documentation'"